version: '3.4'

services:
  mysql_5.7:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: express_mysql_server_5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=express_server
    ports:
      - 3306:3306

  express-server-typescript:
    build: .
    image: express-server-typescript:v1
    container_name: express-server-typescript
    entrypoint: npm start
    depends_on:
      - mysql_5.7
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mysql_5.7
    deploy:
      resources:
        limits:
          memory: 200m
        reservations:
          memory: 150m

networks:
  express-server:
    driver: bridge
